# .bash_profile - login shell configuration:
source ~/.bashrc

# Add `~/bin` & `~/bin/local` to the `$PATH`
if [ -d "$HOME/bin" ]; then
    PATH="$PATH:$HOME/bin/"
fi

if [ -d "$HOME/bin/local" ]; then
    PATH="$PATH:$HOME/bin/local"
fi

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.dotfiles/bash/{path,bash_prompt,exports,bash_aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


# Append to the Bash history file, rather than overwriting it & other history
# prefs
shopt -s histappend;
HISTCONTROL="erasedups:ignoreboth"
HISTIGNORE="clear:exit:cd:pwd:ls:la:ll:lf:lx:history"
HISTSIZE="1000"
HISTFILESIZE="2000"

Shell only exits after the 5th consecutive Ctrl-d
IGNOREEOF=5

export EDITOR="nvim"
export VISUAL="nvim"

# fzf should use the silver searcher
export FZF_DEFAULT_COMMAND='ag -g ""'

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# sonar
PATH="/etc/sonar-scanner/bin:${PATH}"
export PATH

# pyvenv
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
