# .bash_profile - login shell configuration:
source ~/.bashrc

# Add `~/bin` & `~/bin/local` to the `$PATH`
if [ -d "$HOME/bin" ]; then
    PATH="$PATH:$HOME/bin/"
fi

if [ -d "$HOME/bin/local" ]; then
    PATH="$PATH:$HOME/bin/local"
fi

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.dotfiles/bash/{path,bash_prompt,exports,bash_aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# git completion:
if [ -f ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
fi

# Case-insensitive globbing (used in pathname expansion)
#shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it & other history
# prefs
shopt -s histappend;
HISTCONTROL="erasedups:ignoreboth"
HISTIGNORE="clear:exit:cd:pwd:ls:la:ll:lf:lx:history"
HISTSIZE="1000"
HISTFILESIZE="2000"

# Autocorrect typos in path names when using `cd`
#shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
#for option in autocd globstar; do
#	shopt -s "$option" 2> /dev/null;
#done;

# Add tab completion for many Bash commands
#if which brew &> /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
#	source "$(brew --prefix)/share/bash-completion/bash_completion";
#elif [ -f /etc/bash_completion ]; then
#	source /etc/bash_completion;
#fi;

# Enable tab completion for `g` by marking it as an alias for `git`
#if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
#	complete -o default -o nospace -F _git g;
#fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
#[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
#complete -W "NSGlobalDomain" defaults;

# Add `killall` tab completion for common apps
#complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall;

export EDITOR="vim"
export VISUAL="vim"

# mysql
export PATH="/usr/local/mysql/bin/:$PATH"
# export PATH=$PATH:/usr/local/mysql/bin/

# added by Anaconda3 4.3.1 installer
# export PATH="/Users/Russ/anaconda/bin:$PATH"

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# sonar
PATH="/etc/sonar-scanner/bin:${PATH}"
export PATH

# Setting path for syntasic checkers
export PATH="/Users/Russ/.vim/bundle/syntastic.git/syntax_checkers:${PATH}"
# LC_CTYPE=en_US.UTF-8
# export LC_CTYPE

# added by Miniconda3 installer
export PATH="/Users/russellwinch/miniconda3/bin:$PATH"
